/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b4c65016-2b96-40f8-b389-42a7038f8939",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3fvEKGW9m",
    "aws_user_pools_web_client_id": "7k93ikdpafpkfkjmohieibdrls",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://3xdalh6h5bhqzh66vneyfmn33u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-c4crawrl3zfgxnlwdbvn4hyxt4",
    "aws_user_files_s3_bucket": "propertyfa71faab327a4d969e65b47cf3abd399154336-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
